# Generated by Django 3.0.4 on 2022-04-26 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20200516_0228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='title',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='description',
            new_name='job',
        ),
    ]
