# Generated by Django 3.0.4 on 2022-04-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_auto_20220426_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='priority',
        ),
        migrations.AddField(
            model_name='todo',
            name='secondname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
